language: cpp
before_install:
    -   sudo apt-get update
    -   sudo apt-get install libboost-dev
script:
    -   make
    -   ./bin/rshell < pipeTest
compiler: gcc
notifications:
  email:
    recipients:
  
